services:

  postgres-users:
    image: postgres:16
    container_name: markethub-postgres-users
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: markethub
      POSTGRES_PASSWORD: markethub
    ports:
      - "5433:5432"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U markethub -d users_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: markethub-user-service
    environment:
      DATABASE_URL: postgresql+asyncpg://markethub:markethub@postgres-users:5432/users_db
      JWT_SECRET: change-this-secret
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8001:8000"
    depends_on:
      - postgres-users

  redis:
    image: redis:7-alpine
    container_name: markethub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  postgres-products:
    image: postgres:16
    container_name: markethub-postgres-products
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: markethub
      POSTGRES_PASSWORD: markethub
    ports:
      - "5434:5432"
    volumes:
      - products_postgres_data:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U markethub -d products_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-orders:
    image: postgres:16
    container_name: markethub-postgres-orders
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: markethub
      POSTGRES_PASSWORD: markethub
    ports:
      - "5435:5432"
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U markethub -d orders_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  product-service:
    build:
      context: ./product-service
    container_name: markethub-product-service
    environment:
      DATABASE_URL: postgresql+asyncpg://markethub:markethub@postgres-products:5432/products_db
      JWT_SECRET: change-this-secret
      JWT_ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
      INTERNAL_SERVICE_TOKEN: change-this-internal-token
    ports:
      - "8002:8000"
    depends_on:
      - postgres-products
      - redis

  product-service-2:
    build:
      context: ./product-service
    container_name: markethub-product-service-2
    environment:
      DATABASE_URL: postgresql+asyncpg://markethub:markethub@postgres-products:5432/products_db
      JWT_SECRET: change-this-secret
      JWT_ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
      INTERNAL_SERVICE_TOKEN: change-this-internal-token
    depends_on:
      - postgres-products
      - redis

  postgres-notifications:
    image: postgres:16
    container_name: markethub-postgres-notifications
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: markethub
      POSTGRES_PASSWORD: markethub
    ports:
      - "5436:5432"
    volumes:
      - notifications_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U markethub -d notifications_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: markethub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: markethub
      RABBITMQ_DEFAULT_PASS: markethub
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      # Заменяем "ping" на проверку готовности портов
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-service:
    build:
      context: ./notification-service
    container_name: markethub-notification-service
    environment:
      DATABASE_URL: postgresql+asyncpg://markethub:markethub@postgres-notifications:5432/notifications_db
      JWT_SECRET: change-this-secret
      JWT_ALGORITHM: HS256
      RABBITMQ_URL: amqp://markethub:markethub@rabbitmq:5672/
    ports:
      - "8004:8000"
    depends_on:
      postgres-notifications:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    container_name: markethub-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service
      - product-service-2
      - order-service
      - notification-service

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: markethub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - user-service
      - product-service
      - product-service-2
      - order-service
      - notification-service

  grafana:
    image: grafana/grafana:12.1.1
    container_name: markethub-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  order-service:
    build:
      context: ./order-service
    container_name: markethub-order-service
    environment:
      DATABASE_URL: postgresql+asyncpg://markethub:markethub@postgres-orders:5432/orders_db
      JWT_SECRET: change-this-secret
      JWT_ALGORITHM: HS256
      RABBITMQ_URL: amqp://markethub:markethub@rabbitmq:5672/
      PRODUCT_SERVICE_URL: http://product-service:8000
      INTERNAL_SERVICE_TOKEN: change-this-internal-token
    ports:
      - "8003:8000"
    depends_on:
      postgres-orders:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      product-service:
        condition: service_started

volumes:
  users_postgres_data:
  products_postgres_data:
  redis_data:
  orders_postgres_data:
  rabbitmq_data:
  notifications_postgres_data:
  prometheus_data:
  grafana_data: